export const HOME = ""
export const SUBSCRIPTIONS = "subscriptions"
export const HISTORY = "history"
export const VIDEOS = "videos"
export const ACCOUNT = "account"
export const VIDEO = "video"
export const CHANEL = "chanel"
export const SEARCH = "search"